site_name: lisihan's self-website
site_author: lisihan
site_description: lisihan's self-website

nav:
        - Home:
                  - index.md
                  - home:
                            - Home/home.md
        - Blog:
                  - GitHub:
                            - Blog/github_note.md
                  - markdown:
                            - Blog/Markdown syntax specification.md
                  - Dos and Cmd:
                            - Blog/dos-cmd.md
                            - Cmd:
                                      - Blog/cmd.md
                                      - Blog/ping.md
                            - Dos:
                                      - Blog/dos.md
                  - Mathematical modeling:
                            - Blog/Mathematical modeling.md
                            - MATLAB:
                                      - Blog/MATLAB entry.md
                                      - graph theory:
                                                - Blog/graph theory.md
                  - C\C++:
                            - Blog/page6.md
                            - STL:
                                      - Blog/STL.md
                            - 算法与数据结构:
                                      - Blog/first.md
                                      - ACWING:
                                                - Blog/AcWing 3446.md
                                                - Blog/AcWing 3431. skew数.md
                                      - C++ important:
                                                - Blog/C++ important.md
                            - 2023暑假蓝桥杯集训:
                                      - Blog/index_1.md
                                      - C基础:
                                                - Dev-c++:
                                                          - Blog/Dev-c++.md
                                                          - Blog/index_1.md
                                      - C++基础:
                                                - Blog/index_1.md
                                      - 基本数据结构:
                                                - Blog/index_1.md
                                      - 算法:
                                                - Blog/index_1.md
                  - java:
                            - Blog/page7.md
                  - python:
                            - Blog/Python base.md
                            - Blog/python-study-list.md
                            - Blog/python-study-Tuple.md
                            - ML:
                                      - Blog/page2.md
                            - CV:
                                      - Blog/page3.md
                            - NLP:
                                      - Blog/page4.md
                            - jupyter:
                                      - Blog/jupyter-fast.md
                                      - Blog/Jupyter book快捷键.md
        - Website:
                  - Website/build.md
        - E-books:
                  - E-books/pointers on c.md
        - Tag: tag.md

theme:
        name: material
        palette:
                - scheme: default # 日间模式
                  primary: indigo # 上方的
                  accent: red # 链接等可交互元件的高亮色
                  toggle:
                          icon: material/weather-night # 图标
                          name: 切换至夜间模式 # 鼠标悬浮提示
                - scheme: slate # 夜间模式
                  primary: black
                  accent: yellow
                  toggle:
                          icon: material/weather-sunny
                          name: 切换至日间模式
        language: zh # 一些提示性的文字会变成中文
        features:
                - navigation.instant #- header.autohide  #自动隐藏
                - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
                - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
                - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
                # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
                - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
                - navigation.top # 返回顶部的按钮 在上滑时出现
                - search.suggest # 搜索输入一些字母时推荐补全整个单词
                - search.highlight # 搜索出的文章关键词加入高亮
                - navigation.expand # 打开Tab时左侧目录全部展开
                - navigation.indexes #启用节索引页后，可以将文档直接附加到节
                - search.share #搜索分享按钮
                - content.tabs.link
                - content.tooltips
                - content.code.copy
                - content.code.select
                - content.code.select
                - content.action.edit
                - content.action.view
        icon:
                repo: fontawesome/brands/github #右上角图标

edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/bailh/blog-mkdocs # 右上角点击跳转的链接
repo_name: bailh.github.io # 右上角的名字
## [bottom-left corner]
copyright: 李思涵 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]

markdown_extensions:
        - abbr
        - attr_list
        - admonition
        - def_list
        - footnotes
        - md_in_html
        # - meta # 支持Markdown文件上方自定义标题标签等
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.inlinehilite
        - pymdownx.keys
        - pymdownx.mark
        - pymdownx.snippets
        - pymdownx.smartsymbols
        - pymdownx.tilde
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format:
                                    !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件


        - pymdownx.arithmatex: # latex支持
                  generic: true
        - toc:
                  permalink: true # 固定标题位置为当前位置
        - pymdownx.highlight: # 代码块高亮
                  anchor_linenums: true
                  linenums: true # 显示行号
                  # auto_title: true # 显示编程语言名称
        - pymdownx.emoji:
                  emoji_index: !!python/name:materialx.emoji.twemoji
                  emoji_generator: !!python/name:materialx.emoji.to_svg
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.tasklist:
                  custom_checkbox: true
        - markdown.extensions.toc:
                  slugify:
                          !!python/object/apply:pymdownx.slugs.slugify {
                                  kwds: { case: lower },
                          }
                  permalink: "\ue157"

extra:
        generator: false #删除页脚显示“使用 MkDocs 材料制造”
        social:
                - icon: fontawesome/brands/github
                  link: https://bailh.github.io/
                  name: GitHub | Li-Si-Han
                - icon: fontawesome/brands/bilibili
                  link: https://space.bilibili.com/448019332?spm_id_from=333.788.0.0
                  name: Bilibili | -君-莫-笑 # 鼠标悬浮提示
                - icon: fontawesome/solid/paper-plane
                  link: mailto:<bailhsihan@gmail.com> #联系方式
        analytics:
                provider: google
                property: G-XXXXXXXXXX
                feedback:
                        title: Was this page helpful?
                        ratings:
                                - icon: material/emoticon-happy-outline
                                  name: This page was helpful
                                  data: 1
                                  note: >-
                                          Thanks for your feedback!
                                - icon: material/emoticon-sad-outline
                                  name: This page could be improved
                                  data: 0
                                  note: >-
                                          Thanks for your feedback! Help us improve this page by
                                          using our <a href="https://github.com/bailh/blog-mkdocs/issues" target="_blank" rel="noopener">feedback form</a>.

plugins:
        - search:
                  separator: '[\s\u200b\-]'
        - tags:
                  tags_file: tag.md

extra_javascript:
        # - javascripts/extra.js
        - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js # extra的cdn
        - javascripts/mathjax.js
        - https://polyfill.io/v3/polyfill.min.js?features=es6
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
        #- ckplayer/js/ckplayer.js
        # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
        # - javascripts/backgroud.js
        # - javascripts/rellax.min.js
        - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
